### ISSUE TITLE
Not Working In IE

### ISSUE THREAD

**Issue by cool85** [jasonday/plusTabs#1]
this code is great effort, but it is not working in IE.
please solve this problem.

**Comment by jasonday** [comment]
I'll really need more details to debug.
In my testing, it works in ie, down to ie7. 

Were you using full or minified version? and can you do a jsfiddle.net to show the problem?

and what does "not working" mean? (means I need more details).

**Comment by cool85** [comment]
Thanks for your response, i am using IE 9, i need your little help regarding my problem,.

Basically i want to open tabs in one row, if my tabs width/page width is completed than they will be add into the plus tabs, otherwise they will behave like a default. In your example you have open only one tab by default, i have to open more the 10 tabs, i want to show only first 7 tabs, and other 3 would be in plus tabs. If i select any tabs from the plus tab it would be open on tab 7 positions. Please help me regarding this issue.

**Comment by jasonday** [comment]
ok, you are asking for a "feature request".

This is not a bug or an issue with the functionality so saying it does not work in IE9 is not very clear.

 I will consider your request, however it's not likely to be implemented soon.
