### ISSUE TITLE
timeout is not defined

### ISSUE THREAD

**Issue by lbineau** [jasonday/plusTabs#3]
Hello, I'm interested in your plugin.

In your demo http://jsfiddle.net/jasonday/fdhaS/ I get an "error Uncaught ReferenceError: timeout is not defined plusTabs.js:120" (tested in Firefox and Chrome)
Maybe it's a problem from your last update ? Any idea ?

**Comment by jasonday** [comment]
Whoops - missed a variable in the last update. Thanks and you should be all set now.

**Comment by romankubis** [comment]
Hello, same issue in minified version. Btw, usefull plugin.

**Comment by jasonday** [comment]
thanks @romankubis. I'll try and update it soon. Additionally, this plugin is really old - hopefully, I'll get around to updating it.
